In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
from matplotlib.gridspec import GridSpec
from sklearn.decomposition import PCA

In [2]:
data = pd.read_csv('../datos/dataframes_VC/vc_ALL.csv', index_col = 0)
data.index = pd.to_datetime(data.index)

In [3]:
data

                         VC    pblh  u_mean    O3  PM2.5   PM10
2015-01-01 00:00:00     NaN     NaN     NaN   NaN    NaN    NaN
2015-01-01 01:00:00     NaN     NaN     NaN  26.0   81.0  114.0
2015-01-01 02:00:00     NaN     NaN     NaN  27.0   82.0  113.0
2015-01-01 03:00:00     NaN     NaN     NaN  22.0   84.0  114.0
2015-01-01 04:00:00     NaN     NaN     NaN  23.0   80.0  107.0
...                     ...     ...     ...   ...    ...    ...
2015-12-31 19:00:00  1260.0  389.58    3.38  45.0   22.0   62.0
2015-12-31 20:00:00  1207.0  366.02    3.04  38.0   36.0   71.0
2015-12-31 21:00:00  1519.0  347.53    4.22  20.0   34.0   64.0
2015-12-31 22:00:00  1174.0  285.50    4.17  24.0   54.0   88.0
2015-12-31 23:00:00   953.0  352.16    2.73  17.0   43.0   72.0

[52560 rows x 6 columns]